### ISSUE TITLE
How to obtain information from pulse output - electricity measurement

### ISSUE THREAD

**Issue by Tomm206** [kukulich/home-assistant-jablotron100#56]
Hello,

is it please possible to collect information from pulse output using this intregration? I use many Jablotron devices and also Wireless Pulse Convertor JA-150EM-DIN. I cannot find any data in integration. It is also mentioned in the documentation.

Thank you.

**Comment by kukulich** [comment]
Did you add the pulse convertor to integration? Does it log something to the logs?

**Comment by Tomm206** [comment]
Solved. I wrongly set the type of pulse convertor in the integration. I corrected to "Electricity meter with pulse output" and it works. Now it shows pulses in HA – it is cumulative, and it always drops down probably when achieved a max. amount.
Any experience with conversion of these pulses to kWh and display per hour, per day or per month in HA? 
Thanks.
![image](https://user-images.githubusercontent.com/95053956/201040268-7a432977-274f-42be-86a8-9cad7fce9bad.png)

**Comment by DorwinDT** [comment]
> Any experience with conversion of these pulses to kWh and display per hour, per day or per month in HA? Thanks. ![image](https://user-images.githubusercontent.com/95053956/201040268-7a432977-274f-42be-86a8-9cad7fce9bad.png)

did you solved it? I have also pulse  meter attached to jablotron, and would like to see consumption instead of pulses :) of course, I can do this in node-red and create sensor, which do this, but some integration would be better

**Comment by Tomm206** [comment]
Hi, unfortunately not, because the entity that should display data from the electricity meter with pulse output has stopped showing data (it still shows the same number), and I don't know how to correct it. There's probably something wrong with the Jablotron integration.

**Comment by kukulich** [comment]
@Tomm206 You can enable debug, see README, and we can check it.

**Comment by Tomm206** [comment]
I can see now that another sensor was automatically created. The original one doesn't work, but the second one works normally. I didn't know that. So, I will consider now how to convert to kWh.

**Comment by kukulich** [comment]
I suggested something like this to the first user of this sensor:

```
template:
  - sensor:
    - name: 'Energy of Device 36'
      unique_id: energy_device_36
      device_class: energy
      unit_of_measurement: kWh
      state_class: total_increasing
      state: "{{ states('sensor.pulses_of_electricity_meter_with_pulse_output_device_36') | float / 10 }}"

utility_meter:
  hourly_energy_device_36:
    source: sensor.energy_of_device_36
    name: Hourly energy device 36
    cycle: hourly
```

You have to set the right number that means one pulse.
